# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ScannAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScannAR
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'

  target 'ScannARTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScannARUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
